### ISSUE TITLE
Conversion errors

### ISSUE THREAD

**Issue by SamuelSarle** [conreality/wiki.conreality.org#2]
Conversion errors currently found in atleast the following pages:
https://wiki.conreality.org/Glossary (Asterisks around some links)
https://wiki.conreality.org/To-Dos (Broken links)

**Comment by bendiken** [comment]
Fixed in https://github.com/conreality/wiki.conreality.org/commit/8cc1099048f8a8068fd64bfb2d25da6fcfd2a5ad.
